todo:
	latex Informe.tex
	bibtex Informe.aux
	pdflatex Informe.tex
clean:
	rm -f Informe.aux
	rm -f Informe.dvi
	rm -f Informe.log
	rm -f Informe.bbl
	rm -f Informe.blg
	rm -f Informe.lof
	rm -f Informe.lot
	rm -f Informe.toc
	rm -f Informe.out
