# Copyright (c) 2008, Carnegie Mellon University
#     This software is distributed under the terms of the 
#     Simplified BSD License (see tdl/LICENSE.TXT)

ifndef BASE_TDL_DIR
  BASE_TDL_DIR = ..
  export BASE_TDL_DIR
endif

    SRC_FILES = DataVector.java                       \
                DataHashtable.java                    \
                CompilationException.java             \
                DataConstrainedObject.java            \
                DataDestination.java                  \
                DataDestinationAbstractBaseClass.java \
                DataDestinationNull.java              \
                DataDestinationStringBuffer.java      \
                DataDestinationPrintStream.java       \
                DataDestinationFile.java              \
                DataValidateCodeReturnValue.java      \
                DataValidateCode.java                 \
                DataSource.java                       \
                DataSourceString.java                 \
                DataSourceFile.java                   \
                DataSourceNull.java                   \
                DetailedParseException.java           \
                Registry.java                         \
                RunOnSubcomponentInterface.java       \
                RunOnSubcomponent_TdlRefDistributedData.java \
                DataComponent.java                    \
                DataScope.java                        \
                DataClassStructNamespace.java         \
                DataConstraintTagTaskIndexes.java     \
                DataConstraint.java                   \
                DataStatement.java                    \
                DataStatementWithSubstatements.java   \
                DataLabelStatement.java               \
                DataCompoundStatement.java            \
                DataExpression.java                   \
                DataSpawnTask.java                    \
                DataExpressionStatement.java          \
                DataDeclarationStatement.java         \
                DataJumpStatement.java                \
                DataWithDoStatement.java              \
                DataSelectionStatement.java           \
                DataIfElseStatement.java              \
                DataSwitchStatement.java              \
                DataIterationStatement.java           \
                DataWhileStatement.java               \
                DataDoWhileStatement.java             \
                DataForStatement.java                 \
                DataConstraintStatement.java          \
                DataBindTaskStatement.java            \
                DataComponentPlaceholder.java         \
                DataFile.java                         \
                DataTaskArgument.java                 \
                DataTaskDefinition.java               \
                DataExternH.java                      \
                DataDistributedDeclarationSet.java    \
                DataDistributedTypedef.java           \
                DataDistributedStruct.java            \
                DataDistributedEnumEntry.java         \
                DataDistributedEnum.java              \
                TDLtoSMART.java                       \
                TDLC.java                             

include $(BASE_TDL_DIR)/Makefile.generic

