module Parser where

import UU.Parsing
import UU.Scanner.Token
import UU.Scanner.TokenParser
import UU.Scanner.GenTokenOrd()
import UU.Scanner.GenTokenSymbol()
import UU.Scanner.TokenShow()
import UU.Scanner.Position
import Data.List
import UU.Pretty
import System.Environment
import System.IO
import Data.Char

import AttributeGrammar

-- Parser with starting nonterminal Root
-- Semantic functions generated by UUAG
pRoot :: Parser Token T_Root
pRoot
  = sem_Root_Root <$> pDecls

pDecls :: Parser Token T_Decls
pDecls
  = pFoldr_gr (sem_Decls_Cons, sem_Decls_Nil) pDecl

pDecl :: Parser Token T_Decl
pDecl
  =   sem_Decl_Function <$> pSym (T_Var _) <*> many (T_Var _) <* pSym "="
  <|> sem_Decl_Const <$> pSym T_Const <* pSym "="

